export const routes = {
  main: "/",
  login: "/login",
  register: "/register",
  invoices: "/invoices",
  invoicesDetails: "/invoices/:invoiceId/",
  invoicesAddNew: "/invoices/add_new/",
  suppliers: "/suppliers",
  shipments: "/shipments",
  addNewShipments: "/shipments/add_new",
  orders: "/orders",
  ordersDetails: "/orders/:orderId/",
  addNewOrders: "/orders/add_new",
  users: "/users",
  profile: "/profile",
  machinery: "/machinery",
  machineryList: "/machinery/list",
  machineryDetails: "/machinery/list/:machineryId",
  addNewMachinery: "/machinery/list/add_new",
  problems: "/machinery/problems",
  tasks: "/machinery/tasks",
  machineryTaskDetails: "/machinery/tasks/:taskId",
  machineryAddTask: "/machinery/tasks/add_task",
};
