export const routes = {
    main: "/",
    login: "/login",
    register: "/register",
    invoices: "/invoices",
    suppliers: "/suppliers",
    shipments: "/shipments",
    addNewShipments: "/shipments/add_new",
    orders: "/orders",
    addNewOrders: "/orders/add_new",
    users: "/users",
    profile: "/profile",
    machinery: "/machinery",
    addNewMachinery: "/machinery/add_new",
};